affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 3
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 3
symbolic.funs_name.0:
- - sin
  - x^2
  - sin
  - x^2
  - sin
  - x^2
  - sin
  - sin
- - sin
  - x
  - sin
  - sin
  - x^2
  - x^2
  - sin
  - sin
- - sin
  - sin
  - x
  - x^2
  - x
  - x
  - sin
  - sin
- - x
  - x
  - sin
  - x
  - sin
  - sin
  - x
  - x
- - sin
  - sin
  - sin
  - sin
  - sin
  - sin
  - sin
  - sin
symbolic.funs_name.1:
- - x
  - x^2
  - x
  - x
  - x^2
- - x
  - x
  - 1/x
  - x^2
  - x
- - sin
  - x
  - x
  - x
  - x^2
symbolic.funs_name.2:
- - x
  - 1/x
  - x^2
- - x^2
  - 1/x
  - x^2
symbolic_enabled: true
width:
- - 8
  - 0
- - 5
  - 0
- - 3
  - 0
- - 2
  - 0
