affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 2
grid_eps: 0.02
grid_range:
- -1
- 1
k: 5
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 4
symbolic.funs_name.0:
- - sin
  - sin
- - sin
  - x^2
symbolic.funs_name.1:
- - tanh
  - sin
- - x
  - x
symbolic_enabled: true
width:
- - 2
  - 0
- - 2
  - 0
- - 2
  - 0
